name: hermela_andargie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^8.2.0 
  http: ^1.4.0   
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

 